# Generated by Django 5.2.7 on 2025-11-04 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_text', models.TextField(help_text='Análise financeira completa gerada pela IA', verbose_name='Texto da Análise')),
                ('key_insights', models.JSONField(default=list, help_text='Lista de insights principais identificados pela IA', verbose_name='Insights Principais')),
                ('recommendations', models.JSONField(default=list, help_text='Lista de recomendações geradas pela IA', verbose_name='Recomendações')),
                ('period_analyzed', models.CharField(help_text='Período dos dados financeiros analisados', max_length=100, verbose_name='Período Analisado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Análise de IA',
                'verbose_name_plural': 'Análises de IA',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai_aianalys_user_id_07e3a3_idx')],
            },
        ),
    ]
